name: Canary deployment

on:
  workflow_dispatch:

jobs:
  staging-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          git-message: "chore(release): {version}"
          git-user-name: "Changelog triggered by: {{github.actor}}"
          git-branch: "develop"
      - name: Rebase all the changes to canary
        run: |
          git --version
          git fetch origin canary
          git checkout canary
          git rebase develop
          git push origin canary
