name: Deploy to staging

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: What kind of release are we going to make?
        options:
          - major
          - minor
          - patch

jobs:
  staging-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          git-message: "chore(release): {version}"
          git-user-name: "Changelog triggered by: {{github.actor}}"
          git-branch: "develop"

      # - name: Initialize git
      #   run: |
      #     git --version
      #     git config user.name "GitHub Actions Bot Triggered by {{github.actor}}"
      #     git config user.email "<>"
      #     git status
      #     npm version ${{ github.event.inputs.release_type }}
      #     git push origin develop
      #     git describe --tags --abbrev=0 |  git push origin
